//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inlämningsuppgift1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int AdvertID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public string AdvertTitle { get; set; }
        public string AdvertDiscription { get; set; }
        public Nullable<int> AdvertPrice { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
